version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: payload_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payload_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
